// GENERATED by @uniora/server (`UPDATE_DOCS=1 pnpm --filter @uniora/server test`). Do not edit by hand.

/** Any JSON value. */
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface Identity {
  provider: string;
  subject: string;
}

export interface IdentityInput {
  /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
  provider?: string;
  /** The user's stable id in your auth provider. Never an e-mail address. */
  subject: string;
}

export interface Invitation {
  id: string;
  organizationId: string;
  /** Normalized: trimmed and lower-cased. */
  email: string;
  roleIds: string[];
  teamIds: string[];
  invitedBy: Identity;
  /** A `pending` invitation whose `expiresAt` has passed is already unusable. */
  status: "pending" | "accepted" | "revoked" | "expired";
  createdAt: string;
  expiresAt: string;
  acceptedAt?: string;
  acceptedBy?: Identity;
  revokedAt?: string;
  delivery: {
    status: "pending" | "sent" | "failed";
    attempts: number;
    sends: number;
    lastAttemptAt?: string;
    sentAt?: string;
    /** Sanitized. Safe to show an operator. */
    lastError?: string;
  };
}

export interface Member {
  id: string;
  organizationId: string;
  identity: Identity;
  roleIds: string[];
  status: "active" | "suspended" | "blocked";
  createdAt: string;
  updatedAt: string;
  lastActiveAt?: string;
  invitedBy?: Identity;
  /** Present while the member is blocked or suspended. */
  blocked?: {
    at: string;
    until?: string;
  };
  /** Send it back as `If-Match` to refuse changes made from a stale copy. */
  version: number;
}

export interface Organization {
  id: string;
  slug: string;
  name: string;
  /** `suspended` and `archived` organizations are denied every decision. */
  status: "active" | "suspended" | "archived";
  createdAt: string;
  version: number;
}

export interface Policy {
  id: string;
  organizationId: string;
  /** Stable handle, unique in the organization for all time. */
  key: string;
  name: string;
  description?: string;
  kind: "access" | "resource" | "scope" | "feature" | "contextual" | "sensitive";
  /** A policy only restricts: `deny` refuses when the condition holds, `require` refuses unless it holds. */
  effect: "deny" | "require";
  status: "draft" | "active" | "disabled" | "retired";
  /** The revision of the definition. Decisions record it. */
  revision: number;
  /** The normalized definition. */
  definition: Record<string, JsonValue>;
  definitionHash: string;
  createdAt: string;
  createdBy: Identity;
  updatedAt: string;
  statusChange?: {
    at: string;
    by: Identity;
    reason?: string;
  };
  activatedAt?: string;
  /** Send it back as `If-Match` to refuse changes made from a stale copy. */
  version: number;
}

export interface PolicyRevision {
  policyId: string;
  organizationId: string;
  revision: number;
  /** The definition at this revision. */
  definition: Record<string, JsonValue>;
  definitionHash: string;
  createdAt: string;
  createdBy: Identity;
  note?: string;
}

export interface Role {
  id: string;
  organizationId: string;
  key: string;
  name: string;
  /** The protected Owner role: it passes every permission check. */
  isOwnerRole: boolean;
  isSystem: boolean;
  description?: string;
  /** Send it back as `If-Match` to refuse changes made from a stale copy. */
  version: number;
}

export interface RoleSummary {
  id: string;
  organizationId: string;
  key: string;
  name: string;
  /** The protected Owner role: it passes every permission check. */
  isOwnerRole: boolean;
  isSystem: boolean;
  description?: string;
}

export interface Team {
  id: string;
  organizationId: string;
  slug: string;
  name: string;
  status: "active" | "archived";
  /** The team this one sits under. Organizational only: it grants and inherits nothing. */
  parentId?: string;
  /** Your own id for the team in another system. */
  externalId?: string;
  metadata: Record<string, JsonValue>;
  settings: Record<string, JsonValue>;
  createdAt: string;
  updatedAt: string;
  /** Present while the team is archived. */
  archived?: {
    at: string;
    by: Identity;
    reason?: string;
  };
  /** Send it back as `If-Match` to refuse changes made from a stale copy. */
  version: number;
}

export interface TeamMembership {
  id: string;
  organizationId: string;
  teamId: string;
  /** The organization membership. */
  membershipId: string;
  status: "pending" | "active" | "suspended" | "removed";
  /** A label, not a permission. */
  responsibility: "owner" | "manager" | "member";
  /** Roles of the organization that apply only inside this team. */
  roleIds: string[];
  createdAt: string;
  updatedAt: string;
  joinedAt?: string;
  invitedBy?: Identity;
  /** The last status change. */
  statusChange?: {
    at: string;
    by: Identity;
    reason?: string;
  };
  version: number;
}

/** Every operation: what it takes and what it answers. */
export interface Operations {
  /** An organization's audit log */
  "audit.list": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
  };
    output: {
      items: {
        id: string;
        organizationId?: string;
        actor: Identity;
        action: string;
        target?: {
          type: string;
          id: string;
        };
        metadata?: JsonValue;
        createdAt: string;
      }[];
      nextCursor: string | null;
    };
  };
  /** The full decision, with the organization's policies */
  "decisions.authorize": {
    input: {
    /** Who the question is about. */
    identity: {
      /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
      provider?: string;
      /** The user's stable id in your auth provider. Never an e-mail address. */
      subject: string;
    };
    /** The organization the question is about. */
    organizationId: string;
    /** The permission the identity needs. */
    permission: string;
    /** Ask inside this team: it can only narrow the answer. */
    teamId?: string;
    /** The thing the question is about. */
    resource?: {
      /** What kind of resource (`vehicle`, `ticket`): policies are matched on it. */
      type: string;
      /** The resource's id in your database. */
      id: string;
      /** The organization the resource belongs to, as YOUR database says. A mismatch is `cross_tenant_resource`. */
      organizationId: string;
      teamIds?: string[];
      /** The values of the attributes the policies declare (`status`, `ownerIdentity`...). */
      attributes?: Record<string, JsonValue>;
    };
    /** Signals about the request that your server verified (`{ "ipCountry": "ES" }`). Only the ones a policy declares are used. */
    context?: Record<string, JsonValue>;
    /** How the person authenticated, as your server's authentication states it. */
    session?: {
      /** When the person last proved who they are (a sign-in or a step-up), NOT when the session began. */
      authenticatedAt?: string | Date;
      /** When the session began. */
      startedAt?: string | Date;
      /** Whether a second factor was used. */
      mfa?: boolean;
      assuranceLevel?: number;
      methods?: string[];
    };
    /** A protected operation: with no applicable policy the answer is deny. */
    requireApplicablePolicy?: boolean;
  };
    output: {
      /** Check this, not `decision`. */
      allowed: boolean;
      /** Only `allow` lets the operation go on. */
      decision: "allow" | "deny" | "indeterminate";
      /** Why. Stable codes; only ever added. */
      reason: "allowed" | "malformed_input" | "cross_tenant_resource" | "organization_inactive" | "membership_inactive" | "permission_denied" | "policy_denied" | "policy_indeterminate" | "no_applicable_policy" | "evaluation_error" | "policy_set_too_large";
      /** What granted the permission. */
      via?: "membership" | "support_grant";
      policyRevision: number | null;
      /** Present only when stronger or fresher authentication could change the answer. Do not echo the keys to the person. */
      stepUp?: {
        policyKeys: string[];
      };
      evaluatedAt: string;
    };
  };
  /** May this identity do this? */
  "decisions.check": {
    input: {
    /** Who the question is about. */
    identity: {
      /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
      provider?: string;
      /** The user's stable id in your auth provider. Never an e-mail address. */
      subject: string;
    };
    /** The organization the question is about. */
    organizationId: string;
    /** The permission the identity needs. */
    permission?: string;
    /** The feature the organization needs enabled. */
    feature?: string;
    /** Ask inside this team: it can only narrow the answer. */
    teamId?: string;
  };
    output: {
      /** `true` only when every part of the question holds. */
      allowed: boolean;
    };
  };
  /** Several questions about one identity in one round trip */
  "decisions.checkBatch": {
    input: {
    /** Who the question is about. */
    identity: {
      /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
      provider?: string;
      /** The user's stable id in your auth provider. Never an e-mail address. */
      subject: string;
    };
    /** The organization the questions are about. */
    organizationId: string;
    /** At most the server's batch limit (50 unless configured). */
    checks: {
      /** The permission the identity needs. */
      permission?: string;
      /** The feature the organization needs enabled. */
      feature?: string;
      /** Ask inside this team: it can only narrow the answer. */
      teamId?: string;
    }[];
  };
    output: {
      results: {
        allowed: boolean;
      }[];
    };
  };
  /** A bounded set of decisions for a UI, in one call */
  "decisions.snapshot": {
    input: {
    /** Who the question is about. */
    identity: {
      /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
      provider?: string;
      /** The user's stable id in your auth provider. Never an e-mail address. */
      subject: string;
    };
    /** The organization the snapshot is about. */
    organizationId: string;
    permissions?: string[];
    features?: string[];
  };
    output: {
      organizationId: string;
      permissions: Record<string, boolean>;
      features: Record<string, boolean>;
    };
  };
  /** The feature catalog */
  "features.list": {
    input: {
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
  };
    output: {
      items: {
        key: string;
        name: string;
        description?: string;
        defaultEnabled: boolean;
        parentKey?: string;
      }[];
      nextCursor: string | null;
    };
  };
  /** Accept an invitation as the person who just signed in */
  "invitations.accept": {
    input: {
    /** The secret from the accept link. */
    token: string;
    /** Who the question is about. */
    identity: {
      /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
      provider?: string;
      /** The user's stable id in your auth provider. Never an e-mail address. */
      subject: string;
    };
    /** The address the auth provider verified for `identity`. */
    verifiedEmail: string;
  };
    output: {
      invitation: Invitation;
      membershipId: string;
      roleIds: string[];
      rolesSkipped: string[];
      alreadyMember: boolean;
      teamIds: string[];
      teamsSkipped: string[];
    };
  };
  /** Invite someone by e-mail */
  "invitations.create": {
    input: {
    /** The organization. */
    organizationId: string;
    email: string;
    roleIds: string[];
    teamIds?: string[];
    /** Lifetime of this link in milliseconds (30 days at most). */
    ttlMs?: number;
    /** Language hint for the e-mail. */
    locale?: string;
    allowExistingMember?: boolean;
  };
    output: {
      invitation: Invitation;
      acceptUrl?: string | null;
      delivery: {
        status: "sent" | "failed" | "skipped";
        attempts: number;
        error?: string;
      };
      /** `true` when the `Idempotency-Key` was already used for this same request: nothing new was made or sent. */
      replayed?: boolean;
    };
  };
  /** What an accept page may show before sign-in */
  "invitations.preview": {
    input: {
    /** The secret from the accept link. */
    token: string;
  };
    output: {
      organizationName: string;
      email: string;
      roleNames: string[];
      teamNames: string[];
      expiresAt: string;
    };
  };
  /** Send an invitation again */
  "invitations.resend": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The invitation. */
    invitationId: string;
    locale?: string;
    ttlMs?: number;
  };
    output: {
      invitation: Invitation;
      acceptUrl?: string | null;
      delivery: {
        status: "sent" | "failed" | "skipped";
        attempts: number;
        error?: string;
      };
      /** `true` when the `Idempotency-Key` was already used for this same request: nothing new was made or sent. */
      replayed?: boolean;
    };
  };
  /** Revoke an invitation */
  "invitations.revoke": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The invitation. */
    invitationId: string;
  };
    output: Invitation;
  };
  /** Give a member a role */
  "members.assignRole": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The membership (not the user id): `members.list` shows both. */
    membershipId: string;
    /** The role. */
    roleId: string;
  };
    output: Member;
  };
  /** Block a member */
  "members.block": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The membership (not the user id): `members.list` shows both. */
    membershipId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: Member;
  };
  /** Get a member */
  "members.get": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The membership. */
    membershipId: string;
  };
    output: Member;
  };
  /** List an organization's members */
  "members.list": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
    status?: "active" | "suspended" | "blocked";
  };
    output: {
      items: Member[];
      nextCursor: string | null;
    };
  };
  /** Remove a member from the organization */
  "members.remove": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The membership (not the user id): `members.list` shows both. */
    membershipId: string;
  };
    output: {
      removed: boolean;
    };
  };
  /** Suspend a member until a date */
  "members.suspend": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The membership (not the user id): `members.list` shows both. */
    membershipId: string;
    /** When the suspension ends. Must be in the future. */
    until: string | Date;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: Member;
  };
  /** Take a role away from a member */
  "members.unassignRole": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The membership (not the user id): `members.list` shows both. */
    membershipId: string;
    /** The role. */
    roleId: string;
  };
    output: Member;
  };
  /** Lift a block or a suspension */
  "members.unblock": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The membership (not the user id): `members.list` shows both. */
    membershipId: string;
  };
    output: Member;
  };
  /** Create an organization with its first Owner */
  "organizations.create": {
    input: {
    name: string;
    /** URL-safe handle, unique. Derived from the name when omitted. */
    slug?: string;
    /** Who the question is about. */
    owner: {
      /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
      provider?: string;
      /** The user's stable id in your auth provider. Never an e-mail address. */
      subject: string;
    };
  };
    output: {
      organization: Organization;
      ownerRole: Role;
      membership: Member;
      /** `true` when this is the answer to an earlier request with the same `Idempotency-Key`: nothing new was created. */
      replayed?: boolean;
    };
  };
  /** What an organization has unlocked */
  "organizations.features": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
  };
    output: {
      items: ({
        key: string;
        /** What a check sees: the organization's override, else the default, and every parent on. */
        enabled: boolean;
        reason: "enabled" | "disabled" | "default" | "parent_disabled";
        defaultEnabled: boolean;
        parentKey?: string;
        blockedBy?: string;
      })[];
      nextCursor: string | null;
    };
  };
  /** Get an organization */
  "organizations.get": {
    input: {
    /** The organization. */
    organizationId: string;
  };
    output: Organization;
  };
  /** List organizations */
  "organizations.list": {
    input: {
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
    status?: "active" | "suspended" | "archived";
  };
    output: {
      items: Organization[];
      nextCursor: string | null;
    };
  };
  /** The permission catalog */
  "permissions.list": {
    input: {
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
  };
    output: {
      items: {
        key: string;
        name?: string;
        description?: string;
        group?: string;
        implies?: string[];
      }[];
      nextCursor: string | null;
    };
  };
  /** Put a policy live */
  "policies.activate": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The policy. */
    policyId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: Policy;
  };
  /** Create a policy as a draft */
  "policies.create": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Stable handle, unique in the organization for all time. */
    key: string;
    name: string;
    description?: string;
    /** The rule, in the policy language. `POST .../policy-validations` checks one without saving it. */
    definition: Record<string, JsonValue>;
    /** A note kept with this revision of the definition. */
    note?: string;
  };
    output: Policy;
  };
  /** Delete a draft */
  "policies.delete": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The policy. */
    policyId: string;
  };
    output: {
      deleted: boolean;
    };
  };
  /** Switch a policy off */
  "policies.disable": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The policy. */
    policyId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: Policy;
  };
  /** Get a policy */
  "policies.get": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The policy. */
    policyId: string;
  };
    output: Policy;
  };
  /** List an organization's policies */
  "policies.list": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
    status?: "draft" | "active" | "disabled" | "retired";
    kind?: "access" | "resource" | "scope" | "feature" | "contextual" | "sensitive";
    effect?: "deny" | "require";
  };
    output: {
      items: Policy[];
      nextCursor: string | null;
    };
  };
  /** Retire a policy for good */
  "policies.retire": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The policy. */
    policyId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: Policy;
  };
  /** The history of a policy's definition */
  "policies.revisions": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The policy. */
    policyId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
  };
    output: {
      items: PolicyRevision[];
      nextCursor: string | null;
    };
  };
  /** What would be decided? */
  "policies.simulate": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Who the question is about. */
    identity: {
      /** An opaque label for the auth system the subject belongs to (not necessarily its vendor name). Omit it to use the server's default label. */
      provider?: string;
      /** The user's stable id in your auth provider. Never an e-mail address. */
      subject: string;
    };
    permission: string;
    /** Ask inside this team. */
    teamId?: string;
    /** The thing the question is about. */
    resource?: {
      /** What kind of resource (`vehicle`, `ticket`): policies are matched on it. */
      type: string;
      /** The resource's id in your database. */
      id: string;
      /** The organization the resource belongs to, as YOUR database says. A mismatch is `cross_tenant_resource`. */
      organizationId: string;
      teamIds?: string[];
      /** The values of the attributes the policies declare (`status`, `ownerIdentity`...). */
      attributes?: Record<string, JsonValue>;
    };
    /** Signals about the request that your server verified (`{ "ipCountry": "ES" }`). Only the ones a policy declares are used. */
    context?: Record<string, JsonValue>;
    /** How the person authenticated, as your server's authentication states it. */
    session?: {
      /** When the person last proved who they are (a sign-in or a step-up), NOT when the session began. */
      authenticatedAt?: string | Date;
      /** When the session began. */
      startedAt?: string | Date;
      /** Whether a second factor was used. */
      mfa?: boolean;
      assuranceLevel?: number;
      methods?: string[];
    };
    /** Pretend it is this moment (for `environment.*` conditions). */
    at?: string | Date;
    requireApplicablePolicy?: boolean;
    candidate?: {
      /** Replace this policy's definition. */
      policyId?: string;
      /** The definition to try. */
      definition: Record<string, JsonValue>;
    };
  };
    output: {
      /** Check this, not `decision`. */
      allowed: boolean;
      decision: "allow" | "deny" | "indeterminate";
      /** Why. Stable codes; only ever added. */
      reason: string;
      organizationId: string;
      permission: string;
      via?: "membership" | "support_grant";
      policyRevision: number | null;
      stepUp?: {
        policyKeys: string[];
      };
      /** Every policy that applied, with the revision and what it said. */
      policies: JsonValue[];
      evaluatedAt: string;
    };
  };
  /** Edit a policy */
  "policies.update": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The policy. */
    policyId: string;
    name?: string;
    description?: string | null;
    /** The new rule. It becomes a new revision. */
    definition?: Record<string, JsonValue>;
    /** A note kept with this revision of the definition. */
    note?: string;
  };
    output: Policy;
  };
  /** Check a definition without saving it */
  "policies.validate": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The rule to check. */
    definition: Record<string, JsonValue>;
  };
    output: {
      /** The normalized definition. */
      definition: Record<string, JsonValue>;
      hash: string;
      analysis: JsonValue;
    };
  };
  /** Copy a role under a new name */
  "roles.clone": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The role. */
    roleId: string;
    /** Your own id for the copy; generated when omitted. */
    id?: string;
    name: string;
    key?: string;
    description?: string;
  };
    output: Role;
  };
  /** Create a role */
  "roles.create": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Your own id for the role; generated when omitted. */
    id?: string;
    /** Shown to people. */
    name: string;
    /** Stable and URL-safe, unique in the organization. Cannot change later. */
    key?: string;
    description?: string;
    permissionKeys?: string[];
  };
    output: Role;
  };
  /** Delete a role */
  "roles.delete": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The role. */
    roleId: string;
    /** What to do with the holders. */
    members?: "detach" | "reject";
    /** Give the holders this role instead. */
    reassignTo?: string;
  };
    output: {
      deleted: boolean;
    };
  };
  /** Add one permission to a role */
  "roles.grantPermission": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The role. */
    roleId: string;
    /** The permission key. */
    permissionKey: string;
  };
    output: Role;
  };
  /** List an organization's roles */
  "roles.list": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
  };
    output: {
      items: RoleSummary[];
      nextCursor: string | null;
    };
  };
  /** List the permissions a role grants */
  "roles.permissions": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The role. */
    roleId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
  };
    output: {
      items: {
        key: string;
        name?: string;
        description?: string;
        group?: string;
        implies?: string[];
      }[];
      nextCursor: string | null;
    };
  };
  /** Take one permission away from a role */
  "roles.revokePermission": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The role. */
    roleId: string;
    /** The permission key. */
    permissionKey: string;
  };
    output: Role;
  };
  /** Make a role hold exactly these permissions */
  "roles.setPermissions": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The role. */
    roleId: string;
    permissionKeys: string[];
  };
    output: {
      granted: string[];
      revoked: string[];
    };
  };
  /** Rename a role or change its description */
  "roles.update": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The role. */
    roleId: string;
    name?: string;
    description?: string | null;
  };
    output: Role;
  };
  /** Accept a team invitation */
  "teamMembers.accept": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team membership (not the organization membership). */
    teamMembershipId: string;
  };
    output: TeamMembership;
  };
  /** Give a team member a role inside the team */
  "teamMembers.assignRole": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team membership (not the organization membership). */
    teamMembershipId: string;
    /** A role of the organization. */
    roleId: string;
  };
    output: TeamMembership;
  };
  /** Move a member from one team to another */
  "teamMembers.move": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Your own id for the new team membership; generated when omitted. */
    id?: string;
    /** The organization membership that changes team. */
    membershipId: string;
    /** The team. */
    fromTeamId: string;
    /** The team. */
    toTeamId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: TeamMembership;
  };
  /** Lift a team suspension */
  "teamMembers.reactivate": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team membership (not the organization membership). */
    teamMembershipId: string;
  };
    output: TeamMembership;
  };
  /** Remove someone from a team */
  "teamMembers.remove": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team membership (not the organization membership). */
    teamMembershipId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: TeamMembership;
  };
  /** Set who looks after a team */
  "teamMembers.setResponsibility": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team membership (not the organization membership). */
    teamMembershipId: string;
    responsibility: "owner" | "manager" | "member";
  };
    output: TeamMembership;
  };
  /** Suspend a team membership */
  "teamMembers.suspend": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team membership (not the organization membership). */
    teamMembershipId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: TeamMembership;
  };
  /** Take a role away from a team member */
  "teamMembers.unassignRole": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team membership (not the organization membership). */
    teamMembershipId: string;
    /** A role of the organization. */
    roleId: string;
  };
    output: TeamMembership;
  };
  /** Add a member to a team, or invite them */
  "teams.addMember": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
    /** Your own id for the team membership; generated when omitted. */
    id?: string;
    /** The organization membership to add. */
    membershipId: string;
    status?: "pending" | "active";
    responsibility?: "owner" | "manager" | "member";
    roleIds?: string[];
  };
    output: TeamMembership;
  };
  /** Archive a team */
  "teams.archive": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
    /** Why. Kept in the audit log. */
    reason?: string;
  };
    output: Team;
  };
  /** Create a team */
  "teams.create": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Your own id for the team; generated when omitted. */
    id?: string;
    name: string;
    /** URL-safe, unique in the organization; derived from the name when omitted. */
    slug?: string;
    /** Your own id for the team in another system. */
    externalId?: string;
    /** The team this one sits under. */
    parentId?: string;
    metadata?: Record<string, JsonValue>;
    settings?: Record<string, JsonValue>;
  };
    output: Team;
  };
  /** Delete a team */
  "teams.delete": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
  };
    output: {
      deleted: boolean;
    };
  };
  /** Get a team */
  "teams.get": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
  };
    output: Team;
  };
  /** The actor leaves a team, or declines an invitation */
  "teams.leave": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
  };
    output: TeamMembership;
  };
  /** List an organization's teams */
  "teams.list": {
    input: {
    /** The organization. */
    organizationId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    /** Case-insensitive text to look for. */
    q?: string;
    status?: "active" | "archived";
    /** Only the direct sub-teams of this team. */
    parentId?: string;
  };
    output: {
      items: Team[];
      nextCursor: string | null;
    };
  };
  /** List the members of a team */
  "teams.members": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
    /** Items per page. At most the server's maximum (100 unless configured). */
    limit?: number;
    /** The `nextCursor` of the previous page. */
    cursor?: string;
    status?: "pending" | "active" | "suspended" | "removed";
    responsibility?: "owner" | "manager" | "member";
  };
    output: {
      items: TeamMembership[];
      nextCursor: string | null;
    };
  };
  /** Restore an archived team */
  "teams.restore": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
  };
    output: Team;
  };
  /** Edit a team */
  "teams.update": {
    input: {
    /** The organization. */
    organizationId: string;
    /** The team. */
    teamId: string;
    name?: string;
    slug?: string;
    externalId?: string | null;
    parentId?: string | null;
    metadata?: Record<string, JsonValue>;
    settings?: Record<string, JsonValue>;
  };
    output: Team;
  };
}

/** How to call each operation. `safe`: it changes nothing, so a retry is always safe. */
export const OPERATIONS = {
  "audit.list": {
    method: "GET",
    path: "/v1/organizations/:organizationId/audit-log",
    pathParams: ["organizationId"],
    query: ["limit","cursor"],
    body: [],
    hasBody: false,
    scope: "audit:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "decisions.authorize": {
    method: "POST",
    path: "/v1/authorize",
    pathParams: [],
    query: [],
    body: ["identity","organizationId","permission","teamId","resource","context","session","requireApplicablePolicy"],
    hasBody: true,
    scope: "check",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "decisions.check": {
    method: "POST",
    path: "/v1/check",
    pathParams: [],
    query: [],
    body: ["identity","organizationId","permission","feature","teamId"],
    hasBody: true,
    scope: "check",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "decisions.checkBatch": {
    method: "POST",
    path: "/v1/check:batch",
    pathParams: [],
    query: [],
    body: ["identity","organizationId","checks"],
    hasBody: true,
    scope: "check",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "decisions.snapshot": {
    method: "POST",
    path: "/v1/snapshots",
    pathParams: [],
    query: [],
    body: ["identity","organizationId","permissions","features"],
    hasBody: true,
    scope: "check",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "features.list": {
    method: "GET",
    path: "/v1/features",
    pathParams: [],
    query: ["limit","cursor","q"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "invitations.accept": {
    method: "POST",
    path: "/v1/invitations/accept",
    pathParams: [],
    query: [],
    body: ["token","identity","verifiedEmail"],
    hasBody: true,
    scope: "invitations:write",
    delegated: false,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "invitations.create": {
    method: "POST",
    path: "/v1/organizations/:organizationId/invitations",
    pathParams: ["organizationId"],
    query: [],
    body: ["email","roleIds","teamIds","ttlMs","locale","allowExistingMember"],
    hasBody: true,
    scope: "invitations:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: true,
    status: 201,
  },
  "invitations.preview": {
    method: "POST",
    path: "/v1/invitations/preview",
    pathParams: [],
    query: [],
    body: ["token"],
    hasBody: true,
    scope: "invitations:write",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "invitations.resend": {
    method: "POST",
    path: "/v1/organizations/:organizationId/invitations/:invitationId/resend",
    pathParams: ["organizationId","invitationId"],
    query: [],
    body: ["locale","ttlMs"],
    hasBody: true,
    scope: "invitations:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "invitations.revoke": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/invitations/:invitationId",
    pathParams: ["organizationId","invitationId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "invitations:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "members.assignRole": {
    method: "PUT",
    path: "/v1/organizations/:organizationId/members/:membershipId/roles/:roleId",
    pathParams: ["organizationId","membershipId","roleId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "members:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "members.block": {
    method: "POST",
    path: "/v1/organizations/:organizationId/members/:membershipId/block",
    pathParams: ["organizationId","membershipId"],
    query: [],
    body: ["reason"],
    hasBody: true,
    scope: "members:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "members.get": {
    method: "GET",
    path: "/v1/organizations/:organizationId/members/:membershipId",
    pathParams: ["organizationId","membershipId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "members.list": {
    method: "GET",
    path: "/v1/organizations/:organizationId/members",
    pathParams: ["organizationId"],
    query: ["limit","cursor","q","status"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "members.remove": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/members/:membershipId",
    pathParams: ["organizationId","membershipId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "members:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "members.suspend": {
    method: "POST",
    path: "/v1/organizations/:organizationId/members/:membershipId/suspend",
    pathParams: ["organizationId","membershipId"],
    query: [],
    body: ["until","reason"],
    hasBody: true,
    scope: "members:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "members.unassignRole": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/members/:membershipId/roles/:roleId",
    pathParams: ["organizationId","membershipId","roleId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "members:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "members.unblock": {
    method: "POST",
    path: "/v1/organizations/:organizationId/members/:membershipId/unblock",
    pathParams: ["organizationId","membershipId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "members:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "organizations.create": {
    method: "POST",
    path: "/v1/organizations",
    pathParams: [],
    query: [],
    body: ["name","slug","owner"],
    hasBody: true,
    scope: "organizations:create",
    delegated: false,
    safe: false,
    ifMatch: false,
    idempotent: true,
    status: 201,
  },
  "organizations.features": {
    method: "GET",
    path: "/v1/organizations/:organizationId/features",
    pathParams: ["organizationId"],
    query: ["limit","cursor","q"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "organizations.get": {
    method: "GET",
    path: "/v1/organizations/:organizationId",
    pathParams: ["organizationId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "organizations.list": {
    method: "GET",
    path: "/v1/organizations",
    pathParams: [],
    query: ["limit","cursor","q","status"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "permissions.list": {
    method: "GET",
    path: "/v1/permissions",
    pathParams: [],
    query: ["limit","cursor","q"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "policies.activate": {
    method: "POST",
    path: "/v1/organizations/:organizationId/policies/:policyId/activate",
    pathParams: ["organizationId","policyId"],
    query: [],
    body: ["reason"],
    hasBody: true,
    scope: "policies:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "policies.create": {
    method: "POST",
    path: "/v1/organizations/:organizationId/policies",
    pathParams: ["organizationId"],
    query: [],
    body: ["key","name","description","definition","note"],
    hasBody: true,
    scope: "policies:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 201,
  },
  "policies.delete": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/policies/:policyId",
    pathParams: ["organizationId","policyId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "policies:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "policies.disable": {
    method: "POST",
    path: "/v1/organizations/:organizationId/policies/:policyId/disable",
    pathParams: ["organizationId","policyId"],
    query: [],
    body: ["reason"],
    hasBody: true,
    scope: "policies:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "policies.get": {
    method: "GET",
    path: "/v1/organizations/:organizationId/policies/:policyId",
    pathParams: ["organizationId","policyId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: true,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "policies.list": {
    method: "GET",
    path: "/v1/organizations/:organizationId/policies",
    pathParams: ["organizationId"],
    query: ["limit","cursor","q","status","kind","effect"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: true,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "policies.retire": {
    method: "POST",
    path: "/v1/organizations/:organizationId/policies/:policyId/retire",
    pathParams: ["organizationId","policyId"],
    query: [],
    body: ["reason"],
    hasBody: true,
    scope: "policies:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "policies.revisions": {
    method: "GET",
    path: "/v1/organizations/:organizationId/policies/:policyId/revisions",
    pathParams: ["organizationId","policyId"],
    query: ["limit","cursor"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: true,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "policies.simulate": {
    method: "POST",
    path: "/v1/organizations/:organizationId/policy-simulations",
    pathParams: ["organizationId"],
    query: [],
    body: ["identity","permission","teamId","resource","context","session","at","requireApplicablePolicy","candidate"],
    hasBody: true,
    scope: "organizations:read",
    delegated: true,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "policies.update": {
    method: "PATCH",
    path: "/v1/organizations/:organizationId/policies/:policyId",
    pathParams: ["organizationId","policyId"],
    query: [],
    body: ["name","description","definition","note"],
    hasBody: true,
    scope: "policies:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "policies.validate": {
    method: "POST",
    path: "/v1/organizations/:organizationId/policy-validations",
    pathParams: ["organizationId"],
    query: [],
    body: ["definition"],
    hasBody: true,
    scope: "organizations:read",
    delegated: true,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "roles.clone": {
    method: "POST",
    path: "/v1/organizations/:organizationId/roles/:roleId/clone",
    pathParams: ["organizationId","roleId"],
    query: [],
    body: ["id","name","key","description"],
    hasBody: true,
    scope: "roles:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 201,
  },
  "roles.create": {
    method: "POST",
    path: "/v1/organizations/:organizationId/roles",
    pathParams: ["organizationId"],
    query: [],
    body: ["id","name","key","description","permissionKeys"],
    hasBody: true,
    scope: "roles:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 201,
  },
  "roles.delete": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/roles/:roleId",
    pathParams: ["organizationId","roleId"],
    query: ["members","reassignTo"],
    body: [],
    hasBody: false,
    scope: "roles:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "roles.grantPermission": {
    method: "PUT",
    path: "/v1/organizations/:organizationId/roles/:roleId/permissions/:permissionKey",
    pathParams: ["organizationId","roleId","permissionKey"],
    query: [],
    body: [],
    hasBody: false,
    scope: "roles:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "roles.list": {
    method: "GET",
    path: "/v1/organizations/:organizationId/roles",
    pathParams: ["organizationId"],
    query: ["limit","cursor","q"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "roles.permissions": {
    method: "GET",
    path: "/v1/organizations/:organizationId/roles/:roleId/permissions",
    pathParams: ["organizationId","roleId"],
    query: ["limit","cursor","q"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "roles.revokePermission": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/roles/:roleId/permissions/:permissionKey",
    pathParams: ["organizationId","roleId","permissionKey"],
    query: [],
    body: [],
    hasBody: false,
    scope: "roles:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "roles.setPermissions": {
    method: "PUT",
    path: "/v1/organizations/:organizationId/roles/:roleId/permissions",
    pathParams: ["organizationId","roleId"],
    query: [],
    body: ["permissionKeys"],
    hasBody: true,
    scope: "roles:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "roles.update": {
    method: "PATCH",
    path: "/v1/organizations/:organizationId/roles/:roleId",
    pathParams: ["organizationId","roleId"],
    query: [],
    body: ["name","description"],
    hasBody: true,
    scope: "roles:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "teamMembers.accept": {
    method: "POST",
    path: "/v1/organizations/:organizationId/team-memberships/:teamMembershipId/accept",
    pathParams: ["organizationId","teamMembershipId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teamMembers.assignRole": {
    method: "PUT",
    path: "/v1/organizations/:organizationId/team-memberships/:teamMembershipId/roles/:roleId",
    pathParams: ["organizationId","teamMembershipId","roleId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teamMembers.move": {
    method: "POST",
    path: "/v1/organizations/:organizationId/team-moves",
    pathParams: ["organizationId"],
    query: [],
    body: ["id","membershipId","fromTeamId","toTeamId","reason"],
    hasBody: true,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 201,
  },
  "teamMembers.reactivate": {
    method: "POST",
    path: "/v1/organizations/:organizationId/team-memberships/:teamMembershipId/reactivate",
    pathParams: ["organizationId","teamMembershipId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teamMembers.remove": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/team-memberships/:teamMembershipId",
    pathParams: ["organizationId","teamMembershipId"],
    query: ["reason"],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teamMembers.setResponsibility": {
    method: "PUT",
    path: "/v1/organizations/:organizationId/team-memberships/:teamMembershipId/responsibility",
    pathParams: ["organizationId","teamMembershipId"],
    query: [],
    body: ["responsibility"],
    hasBody: true,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teamMembers.suspend": {
    method: "POST",
    path: "/v1/organizations/:organizationId/team-memberships/:teamMembershipId/suspend",
    pathParams: ["organizationId","teamMembershipId"],
    query: [],
    body: ["reason"],
    hasBody: true,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teamMembers.unassignRole": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/team-memberships/:teamMembershipId/roles/:roleId",
    pathParams: ["organizationId","teamMembershipId","roleId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teams.addMember": {
    method: "POST",
    path: "/v1/organizations/:organizationId/teams/:teamId/members",
    pathParams: ["organizationId","teamId"],
    query: [],
    body: ["id","membershipId","status","responsibility","roleIds"],
    hasBody: true,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 201,
  },
  "teams.archive": {
    method: "POST",
    path: "/v1/organizations/:organizationId/teams/:teamId/archive",
    pathParams: ["organizationId","teamId"],
    query: [],
    body: ["reason"],
    hasBody: true,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "teams.create": {
    method: "POST",
    path: "/v1/organizations/:organizationId/teams",
    pathParams: ["organizationId"],
    query: [],
    body: ["id","name","slug","externalId","parentId","metadata","settings"],
    hasBody: true,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 201,
  },
  "teams.delete": {
    method: "DELETE",
    path: "/v1/organizations/:organizationId/teams/:teamId",
    pathParams: ["organizationId","teamId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teams.get": {
    method: "GET",
    path: "/v1/organizations/:organizationId/teams/:teamId",
    pathParams: ["organizationId","teamId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teams.leave": {
    method: "POST",
    path: "/v1/organizations/:organizationId/teams/:teamId/leave",
    pathParams: ["organizationId","teamId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teams.list": {
    method: "GET",
    path: "/v1/organizations/:organizationId/teams",
    pathParams: ["organizationId"],
    query: ["limit","cursor","q","status","parentId"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teams.members": {
    method: "GET",
    path: "/v1/organizations/:organizationId/teams/:teamId/members",
    pathParams: ["organizationId","teamId"],
    query: ["limit","cursor","status","responsibility"],
    body: [],
    hasBody: false,
    scope: "organizations:read",
    delegated: false,
    safe: true,
    ifMatch: false,
    idempotent: false,
    status: 200,
  },
  "teams.restore": {
    method: "POST",
    path: "/v1/organizations/:organizationId/teams/:teamId/restore",
    pathParams: ["organizationId","teamId"],
    query: [],
    body: [],
    hasBody: false,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
  "teams.update": {
    method: "PATCH",
    path: "/v1/organizations/:organizationId/teams/:teamId",
    pathParams: ["organizationId","teamId"],
    query: [],
    body: ["name","slug","externalId","parentId","metadata","settings"],
    hasBody: true,
    scope: "teams:write",
    delegated: true,
    safe: false,
    ifMatch: true,
    idempotent: false,
    status: 200,
  },
} as const;

export type OperationId = keyof typeof OPERATIONS;
