import { createHash, randomUUID } from "node:crypto";
import { createOrganizationWithOwner } from "@uniora/core";
import type { UnioraStorage } from "@uniora/core";
import { ApiError } from "../errors.js";
import { defineRoute } from "../route.js";
import { s } from "../schema.js";
import { IdentityInput } from "./common.js";
import { MemberOut, OrganizationOut, RoleVersionedOut } from "./schemas.js";

/**
 * With an `Idempotency-Key` the ids of what is created are DERIVED from the client and the key, so the organization itself is the
 * record of the first request: a retry (or two at once) meets `organization_exists`, finds what the first one made and answers
 * with it. No separate store to lose, expire or race, and the key is per client (another client's same key makes other ids).
 */
const derive = (clientId: string, key: string, what: string): string => `${what}_${createHash("sha256").update(`${clientId}\0${key}\0${what}`).digest("base64url").slice(0, 24)}`;

const EXISTS = new Set(["organization_exists", "role_exists", "membership_exists"]);
/** The slug derived from the same name is taken by the first attempt itself, and that check can come before the id one. */
const CLASHES = new Set([...EXISTS, "organization_slug_taken"]);

export const provisioningRoutes = [
  defineRoute({
    id: "organizations.create",
    method: "POST",
    path: "/v1/organizations",
    summary: "Create an organization with its first Owner",
    description:
      "The sign-up flow: the organization, its protected Owner role and the founder's membership are created together or not at all. `owner` is the person who signs up, as your auth provider knows them. The ids are generated by the server. Send an `Idempotency-Key` so a retry cannot create a second organization: the same key with the same request answers the first result with `replayed: true`; the same key with a different request is `422 idempotency_key_reused`. The new organization is outside the allowlist of any client that lists organizations, so only a client that may reach every organization can create one.",
    scope: "organizations:create",
    allOrganizations: true,
    status: 201,
    body: s.object({
      name: s.string({ min: 1, max: 255, example: "Acme Motors" }),
      slug: s.optional(s.string({ min: 1, max: 63, description: "URL-safe handle, unique. Derived from the name when omitted.", example: "acme-motors" })),
      owner: IdentityInput,
    }),
    response: s.object({
      organization: OrganizationOut,
      ownerRole: RoleVersionedOut,
      membership: MemberOut,
      replayed: s.optional(s.bool({ description: "`true` when this is the answer to an earlier request with the same `Idempotency-Key`: nothing new was created." })),
    }),
    errors: ["identity_provider_required", "identity_provider_reserved", "organization_slug_taken", "organization_slug_invalid", "idempotency_key_reused"],
    async handler(ctx, { body }) {
      const app = ctx.application();
      const owner = ctx.resolveIdentity(body.owner, "owner");
      const key = ctx.idempotencyKey;
      const clientId = ctx.principal.client.id;
      const ids = key
        ? { organizationId: derive(clientId, key, "org"), ownerRoleId: derive(clientId, key, "role"), membershipId: derive(clientId, key, "mem") }
        : { organizationId: randomUUID(), ownerRoleId: randomUUID(), membershipId: randomUUID() };

      try {
        return (await app.storage.transaction(async (tx) => {
          // The founding flow opens its own transaction; reuse this one so the organization, its Owner and the audit entry commit together.
          const nested = { ...tx, transaction: <T>(callback: (inner: typeof tx) => Promise<T>) => callback(tx) } as unknown as UnioraStorage;
          const created = await createOrganizationWithOwner(nested, {
            organizationId: ids.organizationId,
            organizationName: body.name,
            ...(body.slug !== undefined ? { organizationSlug: body.slug } : {}),
            ownerRoleId: ids.ownerRoleId,
            membershipId: ids.membershipId,
            ownerIdentity: owner,
          });
          await tx.auditLogs.record({
            id: randomUUID(),
            organizationId: created.organization.id,
            actor: app.principal,
            action: "organization.created",
            target: { type: "organization", id: created.organization.id },
            metadata: { name: created.organization.name, slug: created.organization.slug, owner },
          });
          return created;
        })) as never;
      } catch (error) {
        const code = (error as { code?: string }).code;
        if (!key || code === undefined || !CLASHES.has(code)) throw error;
        // Same key as an earlier request: it is a replay only if it is the SAME request.
        const storage = ctx.config.storage;
        const organization = await storage.organizations.findById(ids.organizationId);
        const membership = await storage.memberships.findById(ids.membershipId);
        const [ownerRole] = await storage.roles.findByIds([ids.ownerRoleId]);
        if (!organization || !membership || !ownerRole) {
          // Nothing of this key exists (yet): a real clash with someone else's slug, or the first request still being written.
          if (code === "organization_slug_taken") throw error;
          throw new ApiError(409, "idempotency_in_progress", { headers: { "Retry-After": "1" } });
        }
        const same =
          organization.name === body.name &&
          (body.slug === undefined || organization.slug === body.slug) &&
          membership.identity.provider === owner.provider &&
          membership.identity.subject === owner.subject;
        if (!same) throw new ApiError(422, "idempotency_key_reused");
        return { organization, ownerRole, membership, replayed: true } as never;
      }
    },
  }),
];
