import { COMPONENT_SCHEMAS } from "./routes/components.js";
import { allRoutes } from "./routes/index.js";
import type { Route } from "./route.js";
import type { ObjectSchema, Schema } from "./schema.js";

type Side = "input" | "output";

const ident = (name: string): string => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name));

/** The TypeScript type of a schema, as a request carries it (`input`: a date may be a `Date`) or as a response has it (`output`: text). */
function render(schema: Schema, side: Side, refs: ReadonlyMap<Schema, string> | undefined, indent: string): string {
  const named = refs?.get(schema);
  if (named !== undefined) return named;
  const next = `${indent}  `;
  switch (schema.kind) {
    case "optional":
      return render(schema.inner, side, refs, indent);
    case "nullable":
      return `${render(schema.inner, side, refs, indent)} | null`;
    case "string":
      return "string";
    case "int":
      return "number";
    case "bool":
      return "boolean";
    case "date":
      return side === "input" ? "string | Date" : "string";
    case "enum":
      return schema.values.map((value) => JSON.stringify(value)).join(" | ");
    case "array": {
      const item = render(schema.item, side, refs, indent);
      return /[|&]/.test(item) ? `(${item})[]` : `${item}[]`;
    }
    case "object": {
      const entries = Object.entries(schema.shape);
      if (entries.length === 0) return "Record<string, never>";
      const lines = entries.map(([key, inner]) => {
        const description = (inner.kind === "optional" ? inner.inner : inner) as { description?: string };
        const doc = description.description ? `${next}/** ${description.description.replace(/\*\//g, "* /")} */\n` : "";
        return `${doc}${next}${ident(key)}${inner.kind === "optional" ? "?" : ""}: ${render(inner, side, refs, next)};`;
      });
      return `{\n${lines.join("\n")}\n${indent}}`;
    }
    case "record":
      return `Record<string, ${render(schema.value, side, refs, indent)}>`;
    case "json":
      return "JsonValue";
  }
}

const shapeOf = (schema: ObjectSchema | undefined): Record<string, Schema> => (schema ? { ...schema.shape } : {});
const isOptional = (schema: Schema): boolean => schema.kind === "optional";

/** The part of an operation's input that comes from the path, the query and the body, flattened into one object. */
function inputOf(route: Route): { type: string; pathParams: string[]; query: string[]; body: string[]; required: boolean } {
  const params = shapeOf(route.params);
  const query = shapeOf(route.query);
  const body = shapeOf(route.body);
  const all = { ...params, ...query, ...body };
  const names = [...Object.keys(params), ...Object.keys(query), ...Object.keys(body)];
  if (new Set(names).size !== names.length) throw new Error(`Route ${route.id}: a name is used in more than one of path, query and body, so the client could not flatten them.`);
  const lines = Object.entries(all).map(([key, schema]) => {
    const inner = (schema.kind === "optional" ? schema.inner : schema) as { description?: string };
    const doc = inner.description ? `    /** ${inner.description.replace(/\*\//g, "* /")} */\n` : "";
    return `${doc}    ${ident(key)}${isOptional(schema) ? "?" : ""}: ${render(schema, "input", undefined, "    ")};`;
  });
  return {
    type: lines.length === 0 ? "Record<string, never>" : `{\n${lines.join("\n")}\n  }`,
    pathParams: Object.keys(params),
    query: Object.keys(query),
    body: Object.keys(body),
    required: Object.values(all).some((schema) => !isOptional(schema)),
  };
}

/**
 * The typed surface of `@uniora/client`, generated from the route table: one entry per operation with its input (path, query and
 * body flattened), its output, and what the client needs to call it (method, path, whether a retry is safe). A route cannot be
 * added, changed or removed without this file changing, and `codegen.test.ts` fails until it is regenerated.
 */
export function generateClientSource(routes: readonly Route[] = allRoutes()): string {
  const sorted = [...routes].sort((a, b) => a.id.localeCompare(b.id));
  const out: string[] = [];
  out.push("// GENERATED by @uniora/server (`UPDATE_DOCS=1 pnpm --filter @uniora/server test`). Do not edit by hand.");
  out.push("");
  out.push("/** Any JSON value. */");
  out.push("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };");
  out.push("");
  for (const [schema, name] of [...COMPONENT_SCHEMAS].sort((a, b) => a[1].localeCompare(b[1]))) {
    const others = new Map([...COMPONENT_SCHEMAS].filter(([, other]) => other !== name));
    out.push(`export interface ${name} ${render(schema, "output", others, "")}`);
    out.push("");
  }
  out.push("/** Every operation: what it takes and what it answers. */");
  out.push("export interface Operations {");
  for (const route of sorted) {
    const input = inputOf(route);
    out.push(`  /** ${route.summary} */`);
    out.push(`  ${JSON.stringify(route.id)}: {`);
    out.push(`    input: ${input.type};`);
    out.push(`    output: ${route.status === 204 ? "void" : render(route.response, "output", COMPONENT_SCHEMAS, "    ")};`);
    out.push("  };");
  }
  out.push("}");
  out.push("");
  out.push("/** How to call each operation. `safe`: it changes nothing, so a retry is always safe. */");
  out.push("export const OPERATIONS = {");
  for (const route of sorted) {
    const input = inputOf(route);
    out.push(`  ${JSON.stringify(route.id)}: {`);
    out.push(`    method: ${JSON.stringify(route.method)},`);
    out.push(`    path: ${JSON.stringify(route.path)},`);
    out.push(`    pathParams: ${JSON.stringify(input.pathParams)},`);
    out.push(`    query: ${JSON.stringify(input.query)},`);
    out.push(`    body: ${JSON.stringify(input.body)},`);
    out.push(`    hasBody: ${route.body !== undefined},`);
    out.push(`    scope: ${JSON.stringify(route.scope)},`);
    out.push(`    delegated: ${route.delegated},`);
    out.push(`    safe: ${!route.write},`);
    out.push(`    ifMatch: ${route.ifMatch},`);
    out.push(`    idempotent: ${route.idempotent},`);
    out.push(`    status: ${route.status},`);
    out.push("  },");
  }
  out.push("} as const;");
  out.push("");
  out.push("export type OperationId = keyof typeof OPERATIONS;");
  out.push("");
  return out.join("\n");
}
