/**
 * The standard audit action names UNIORA itself records, as `<object>.<past-tense verb>`. A host can record its own
 * actions through `auditLogs.record` (use its own namespace, e.g. `billing.invoice_paid`); these are the ones the
 * library emits, so a dashboard or an alert can rely on the spelling.
 */
export const AUDIT_ACTIONS = [
  "organization.created",
  "organization.renamed",
  "organization.updated",
  "organization.status_changed",
  "organization.ownership_transferred",
  "membership.created",
  "membership.deleted",
  "membership.left",
  "membership.blocked",
  "membership.suspended",
  "membership.unblocked",
  "membership.role_assigned",
  "membership.role_unassigned",
  "membership.owner_role_assigned",
  "membership.owner_role_unassigned",
  "role.created",
  "role.owner_created",
  "role.renamed",
  "role.updated",
  "role.cloned",
  "role.permissions_replaced",
  "role.deleted",
  "role.permission_granted",
  "role.permission_revoked",
  "permission.registered",
  "permission.unregistered",
  "feature.registered",
  "feature.unregistered",
  "feature.enabled",
  "feature.disabled",
  "feature.bulk_changed",
  "feature.disabled_everywhere",
  "entitlement.defined",
  "entitlement.removed",
  "entitlement.limit_changed",
  "entitlement.limit_cleared",
  "support_grant.created",
  "support_grant.revoked",
  "team.created",
  "team.updated",
  "team.archived",
  "team.restored",
  "team.deleted",
  "team.owner_changed",
  "team.manager_changed",
  "team_member.added",
  "team_member.invited",
  "team_member.accepted",
  "team_member.reactivated",
  "team_member.suspended",
  "team_member.removed",
  "team_member.role_assigned",
  "team_member.role_unassigned",
  "invitation.created",
  "invitation.resent",
  "invitation.revoked",
  "invitation.accepted",
  "invitation.delivery_failed",
  "identity_link.created",
  "identity_link.removed",
  "audit_log.pruned",
  "platform.bootstrapped",
  "platform.role_created",
  "platform.role_updated",
  "platform.role_deleted",
  "platform.member_added",
  "platform.member_suspended",
  "platform.member_reactivated",
  "platform.member_removed",
  "platform.member_role_assigned",
  "platform.member_role_unassigned",
  "platform.organization_status_changed",
  "platform.support_access_granted",
  "platform.support_access_revoked",
  "platform.change_refused",
  "access.change_refused",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

const STANDARD = new Set<string>(AUDIT_ACTIONS);

/** Whether `action` is one of the names UNIORA itself records. */
export function isStandardAuditAction(action: string): action is AuditAction {
  return STANDARD.has(action);
}
